research_task:
  description: >
    Conduct comprehensive research about {topic} using the RAG Search Tool to gather relevant 
    information from the knowledge base. Focus on:
    1. Key concepts and definitions
    2. Important features and functionalities  
    3. Best practices and common use cases
    
    Use the RAG Search Tool at most 3 times with different queries to ensure comprehensive coverage.
  expected_output: >
    A comprehensive research document with:
    - Key topics about {topic} with detailed explanations
    - Sources and references from the knowledge base
    Formatted as structured text without markdown code blocks.
  agent: researcher

reporting_task:
  description: >
    Based on the research findings, create a comprehensive quiz about {topic}. 
    Use the RAG Search Tool to verify information and get additional context when needed.
    
    Generate exactly {number_of_questions} questions based on the question_type: {question_type}
    
    Question type distribution:
    - "Multiple Choice": All questions are multiple choice with 4 options each
    - "True/False": All questions are true/false with 2 options (True, False)
    - "Short Open Answer": All questions are open-ended questions
    - "mixed": Distribute questions as: 33.3% multiple choice, 33.3% true/false, 33.3% open-ended (round appropriately)
    
    Create questions that cover:
    1. Fundamental concepts (30% of questions)
    2. Practical applications (40% of questions) 
    3. Advanced scenarios and troubleshooting (30% of questions)
    
    For each question:
    - Provide clear, unambiguous question text
    - For multiple choice: include exactly 4 options
    - For true/false: include exactly 2 options ["True", "False"]
    - For open-ended: leave answer field empty
    - Include the correct answer for multiple choice and true/false questions
    
  expected_output: >
    A JSON object with the following exact structure:
    {{
      "questions": [
        {{
          "type": "multiple_choice|true_false|open|mixed",
          "question": "question text",
          "options": ["option1", "option2", "option3", "option4"] OR ["True", "False"] OR [],
          "answer": "correct answer text" OR ""
        }}
      ]
    }}
    
    Important requirements:
    - Output ONLY valid JSON, no additional text or markdown formatting
    - Use "multiple_choice", "true_false", or "open_ended" for type field
    - For multiple_choice: provide 4 options, answer should match one option exactly
    - For true_false: provide ["True", "False"] as options, answer should be "True" or "False"
    - For open_ended: provide empty array [] for options and empty string "" for answer
    - Generate exactly {number_of_questions} questions total

    Do NOT include JSON code blocks (```).
  agent: reporting_analyst
