research_task:
  description: >
    Conduct comprehensive research about {topic} using the RAG Search Tool to gather relevant 
    information from the knowledge base. Focus on:
    1. Key concepts and definitions
    2. Important features and functionalities  
    3. Best practices and common use cases
    
    Use the RAG Search Tool at most 3 times with different queries to ensure comprehensive coverage.
  expected_output: >
    A comprehensive research document with:
    - Key topics about {topic} with detailed explanations
    - Sources and references from the knowledge base
    Formatted as structured text without markdown code blocks.
  agent: researcher

reporting_task:
  description: >
    Based on the research findings, create a comprehensive quiz about {topic}. 
    Use the RAG Search Tool to verify information and get additional context when needed.
    
    Use the FileReadTool to read the provided Markdown quiz template. 
    Strictly analyze the structure of that template and generate questions that 
    exactly match the number and type of placeholders it contains 
    (True/False, Multiple Choice, Open-ended). 
    Ensure the output respects the required JSON schema.
    
    For each question:
    - Provide clear, unambiguous question text
    - Include the correct answer for all types of questions
    
    Create questions that cover:
    1. Fundamental concepts
    2. Practical applications 
    3. Advanced scenarios and troubleshooting
    
  expected_output: >
    A JSON object with the following exact structure:
    {{
      "questions": [
        {{
          "type": "multiple_choice|true_false|open|mixed",
          "question": "question text",
          "options": ["option1", "option2", "option3", "option4"] OR ["True", "False"] OR [],
          "answer": "correct answer text"
        }}
      ]
    }}
    
    Important requirements:
    - Output ONLY valid JSON, no additional text or markdown formatting
    - Use "multiple_choice", "true_false", or "open_ended" for type field
    - For multiple_choice: provide 4 options, answer should match one option exactly
    - For true_false: provide ["True", "False"] as options, answer should be "True" or "False"
    - For open_ended: provide empty array [] for options
    - Generate exactly {number_of_questions} questions total

    Do NOT include JSON code blocks (```).
  agent: reporting_analyst
