quiz_maker_task:
  description: |
    The JSON input: "{questions}" has the following structure:
 
    {
      "questions": [
        {
          "type": "<multiple | true_false | open>",
          "question": "<question text>",
          "options": ["<list of options>", "..."],
          "answer": "<correct answer or 'n/a'>"
        }
      ]
    }

    Placeholders are enclosed in square braces e.g. [TF_Question_1], [MC_Question_1], [MC_Option_A_1], [Open_Question_1]

    Populate the base Markdown quiz template following the following rules:
    - For each T/F question, replace the T/F question placeholder with the actual question text.
    - For each multiple choice question, replace the MC question placeholder with the actual question text and the A-D placeholders with the actual options.
    - For each open-ended question, replace the open question placeholder with the actual question text.

    Output only the final Markdown content of the populated quiz pack.
  expected_output: >
    A Markdown quiz pack populated with all questions from the JSON file.
    Do not include Markdown code blocks (```).
  agent: quiz_maker

pdf_export_task:
  description: |
    Take the Markdown quiz content generated by the previous task and convert it into a PDF using the provided tool.
    Follow these formatting guidelines:

    Requirements:
    - Paper size: A4
    - Margins: ~2 cm
    - Preserve headings, lists, and formatting
 
    Output a success message indicating the location of the saved PDF file.
  expected_output: >
    A success message indicating the location of the saved PDF file.
  agent: quiz_maker
  context: [quiz_maker_task]
