quiz_maker_task:
  description: |
    Read the JSON file 'outputs/questions.json' using FileReadTool that has the following structure:
 
    {
      "questions": [
        {
          "type": "multiple_choice|true_false|open|mixed",
          "question": "<question text>",
          "options": ["<list of options>", "..."] OR ["True", "False"] OR [],
          "answer": "<correct answer or empty string>"
        }
      ]
    }

    Also read the quiz template file 'outputs/quiz_template.md' using FileReadTool which contains placeholders like:
    [TF_Question_1], [MC_Question_1], [MC_Option_A_1], [Open_Question_1]

    Populate the base Markdown quiz template following these rules:
    - For each true_false question, replace the T/F question placeholder with the actual question text.
    - For each multiple_choice question, replace the MC question placeholder with the actual question text and the A-D placeholders with the actual options.
    - For each short open question, replace the open question placeholder with the actual question text.
    - Maintain the original template structure and formatting
    - Replace placeholders in sequential order (question 1, 2, 3, etc.)

    Output only the final Markdown content of the populated quiz pack.
  expected_output: >
    A Markdown quiz pack populated with all questions from the JSON file.
    Do not include Markdown code blocks (```).
  agent: quiz_maker

pdf_export_task:
  description: |
    Take the Markdown quiz content generated by the previous task and convert it into a PDF using the provided tool.
    Follow these formatting guidelines:

    Requirements:
    - Paper size: A4
    - Margins: ~2 cm
    - Preserve Markdown headings, lists, formatting, new lines
    - Number questions starting from 1 and finish at {number_of_questions}, continuously across sections

    Output a success message indicating the location of the saved PDF file.
  expected_output: >
    A success message indicating the location of the saved PDF file.
  agent: quiz_maker
  context: [quiz_maker_task]