services:
  quiz-generator:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - azure_credentials
    container_name: quiz-generator-app
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      # Mount outputs directory to persist generated files
      - ./outputs:/app/outputs
      # Mount dataset directory for access to training data
      - ./src/quiz_generator/dataset:/app/src/quiz_generator/dataset
      # Mount MLflow runs for persistence
      - mlflow_data:/app/mlruns
    environment:
      # MLflow tracking - using local file system for now
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      # Add other environment variables as needed
      - PYTHONPATH=/app/src
      # Qdrant connection
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      # Expose port if your app has a web interface
      - "8000:8000"
    networks:
      - quiz-network
    restart: unless-stopped

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

secrets:
  azure_credentials:
    file: .secrets/azure_credentials.txt

volumes:
  qdrant_data:
  mlflow_data:

networks:
  quiz-network:
    driver: bridge